services:
  - type: web
    name: test-mern
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    repo: https://github.com/thejaAshwin62/test-mern-cl
    branch: main
    envVars:
      - key: PORT
        value: "1000"
        generateValue: false
    healthCheckPath: /
    numInstances: 1
